broadcasting:
  enabled: false
  mode: "REDIS"
  only-on-change: false
  updating-interval: 1000
  targets:
    - type: "REDIS"
      set-key: "proxyonlinelinker:online"
      server-id: "lobby1"
      expire-seconds: 60

status:
  enabled: false
  global-cache-expiration: 1500
  request-on-demand: false
  sources:
    - type: "PING"
      host: "localhost"
      port: 25566
      timeout: 5000
      cache-expiration: -1

  replacement:
    strategy: "DELEGATE"

redis:
  mode: "standalone"
  username: ""
  password: ""
  database: 0
  timeout-millis: 2000
  max-attempts: 3
  max-total-retries-duration: 15000
  standalone:
    host: "localhost"
    port: 6379
  sentinel:
    masterName: "mymaster"
    sentinels:
      - "sentinel1.example.com:26379"
      - "sentinel2.example.com:26379"
  cluster:
    cluster-nodes:
      - "node1.example.com:7000"
      - "node2.example.com:7001"