general:

broadcasting:
  enabled: false
  mode: "REDIS"

status:
  enabled: false
  global-cache-expiration: 1500
  request-on-demand: false
  sources:
    - type: "PING"
      host: "localhost"
      port: 25566
      timeout: 5000
      cache-expiration: -1

  replacement:
    strategy: "DELEGATE"